# canton-zk-attestation/prover/main.py
#
# To run this server:
# 1. Install dependencies:
#    pip install "fastapi[all]" python-dotenv
#
# 2. Make sure you have `node` and `snarkjs` installed and in your system's PATH.
#    npm install -g snarkjs
#
# 3. Ensure your Circom circuits have been compiled. From the project root:
#    (cd circuits && ./compile_all.sh)
#
# 4. Run the prover server from the project root:
#    python prover/main.py
#
# The server will be available at http://127.0.0.1:8000

import os
import json
import subprocess
import tempfile
from typing import List, Dict, Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
import uvicorn

# --- Configuration ---
# Assumes this script is run from the project root directory.
# Adjust paths if running from the `prover` directory itself.
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
CIRCUITS_BUILD_DIR = os.path.join(PROJECT_ROOT, "circuits", "build")

# Define available circuits and their required inputs. This acts as a simple registry.
AVAILABLE_CIRCUITS = {
    "balance_threshold": {
        "wasm": os.path.join(CIRCUITS_BUILD_DIR, "balance_threshold_js", "balance_threshold.wasm"),
        "zkey": os.path.join(CIRCUITS_BUILD_DIR, "circuit_final.zkey"),
        "private_inputs": ["balance"],
        "public_inputs": ["threshold", "partyHash"],
    },
    "kyc_credential": {
        "wasm": os.path.join(CIRCUITS_BUILD_DIR, "kyc_credential_js", "kyc_credential.wasm"),
        "zkey": os.path.join(CIRCUITS_BUILD_DIR, "circuit_final.zkey"),
        "private_inputs": ["kycId", "countryCode"],
        "public_inputs": ["allowedCountryCode", "issuerHash"],
    },
    "collateral_ratio": {
        "wasm": os.path.join(CIRCUITS_BUILD_DIR, "collateral_ratio_js", "collateral_ratio.wasm"),
        "zkey": os.path.join(CIRCUITS_BUILD_DIR, "circuit_final.zkey"),
        "private_inputs": ["collateralValue", "debtValue"],
        "public_inputs": ["minRatio", "positionIdHash"],
    },
}

# --- Pydantic Models for API Data Contracts ---

class GenerateProofRequest(BaseModel):
    circuit_name: str = Field(..., description="The name of the circuit to use, e.g., 'balance_threshold'.")
    inputs: Dict[str, Any] = Field(..., description="A dictionary of all private and public inputs for the circuit.")

class SnarkJSProof(BaseModel):
    """
    Represents the structure of a Groth16 proof generated by snarkjs.
    This structure is directly compatible with the Verifier Daml template.
    """
    pi_a: List[str]
    pi_b: List[List[str]]
    pi_c: List[str]
    protocol: str
    curve: str

class GenerateProofResponse(BaseModel):
    proof: SnarkJSProof
    public_signals: List[str]


# --- FastAPI Application ---
app = FastAPI(
    title="Canton ZK Prover Service",
    description="Generates ZK-SNARK proofs for private data attestation on Canton.",
    version="1.0.0",
)

# --- Helper Functions ---

def run_command(command: List[str], cwd: str) -> None:
    """Executes a shell command, raising an HTTPException on failure."""
    try:
        process = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            cwd=cwd,
        )
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail=f"Command not found: {command[0]}. Is it installed and in your PATH?")
    except subprocess.CalledProcessError as e:
        error_message = f"Command '{' '.join(command)}' failed with exit code {e.returncode}.\n"
        error_message += f"Stderr: {e.stderr.strip()}"
        raise HTTPException(status_code=500, detail=error_message)


# --- API Endpoints ---

@app.get("/health")
async def health_check():
    """Simple health check endpoint to verify the service is running and can find its circuit artifacts."""
    status = {}
    for name, config in AVAILABLE_CIRCUITS.items():
        status[name] = {
            "wasm_found": os.path.exists(config["wasm"]),
            "zkey_found": os.path.exists(config["zkey"]),
        }
    return {"status": "ok", "circuits": status}


@app.post("/generate-proof", response_model=GenerateProofResponse)
async def generate_proof(request: GenerateProofRequest):
    """
    Generates a Groth16 ZK-SNARK proof using snarkjs.

    This endpoint takes the name of a pre-compiled circuit and the necessary inputs.
    It then orchestrates the `snarkjs` command-line tools to generate a witness,
    create a proof, and return the proof along with the public signals.
    """
    circuit_name = request.circuit_name
    if circuit_name not in AVAILABLE_CIRCUITS:
        raise HTTPException(status_code=404, detail=f"Circuit '{circuit_name}' is not supported.")

    circuit_config = AVAILABLE_CIRCUITS[circuit_name]
    wasm_path = circuit_config["wasm"]
    zkey_path = circuit_config["zkey"]

    if not os.path.exists(wasm_path) or not os.path.exists(zkey_path):
        raise HTTPException(status_code=503, detail=f"Compiled artifacts for circuit '{circuit_name}' not found on server. Please compile circuits first.")

    required_inputs = circuit_config["private_inputs"] + circuit_config["public_inputs"]
    if not all(key in request.inputs for key in required_inputs):
        missing = set(required_inputs) - set(request.inputs.keys())
        raise HTTPException(status_code=400, detail=f"Missing required inputs for '{circuit_name}': {', '.join(missing)}")

    # Use a temporary directory to handle concurrent requests safely.
    with tempfile.TemporaryDirectory() as temp_dir:
        input_file = os.path.join(temp_dir, "input.json")
        witness_file = os.path.join(temp_dir, "witness.wtns")
        proof_file = os.path.join(temp_dir, "proof.json")
        public_file = os.path.join(temp_dir, "public.json")

        # Step 1: Write inputs to a JSON file for snarkjs.
        with open(input_file, 'w') as f:
            json.dump(request.inputs, f, indent=2)

        # Step 2: Generate the witness using the circuit's WASM file.
        witness_command = ["snarkjs", "witness", "calculate", wasm_path, input_file, witness_file]
        run_command(witness_command, temp_dir)

        # Step 3: Generate the Groth16 proof using the witness and proving key.
        proof_command = ["snarkjs", "groth16", "prove", zkey_path, witness_file, proof_file, public_file]
        run_command(proof_command, temp_dir)

        # Step 4: Read and return the generated proof and public signals.
        with open(proof_file, 'r') as f:
            proof_data = json.load(f)
        with open(public_file, 'r') as f:
            public_signals = json.load(f)

    return GenerateProofResponse(
        proof=SnarkJSProof(**proof_data),
        public_signals=public_signals
    )


# --- Main Execution Block ---
if __name__ == "__main__":
    print("--- Canton ZK Prover Service ---")
    print(f"Project Root: {PROJECT_ROOT}")
    print(f"Searching for circuits in: {CIRCUITS_BUILD_DIR}")
    print("-" * 34)
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="info")